In [8]:
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import joblib
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [28]:
import os
import pandas as pd

file = r"C:\Users\Usuario\Desktop\ING.MTTO IND\Repositorio\Reboiler_Raw_Data_With_Timestamps.xlsx"

df1 = pd.read_excel(file, header=0)

attrs = {
    'var': 'df1',
    'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Fecha,VAL356CI8017-Conductividad,VAL356M003-Carga Motor,VAL356M014-Carga Motor,VAL356M015-Carga Motor,VAL356PI8026-Ind.Presión,VAL356PIC8025-Ind.Presión,VAL356TI8015-Ind.Temperatura,VAL356TIC8014-Ind.Temperatura,Estado
0,2006-10-24 23:38:00,12.3,68.026459,45.670056,30.343173,21.492553,20.9,71.883617,103.414846,0
1,2006-10-25 01:38:00,18.9,68.827098,45.924569,30.126654,20.954956,20.6,72.301453,103.487449,0
2,2006-10-25 03:38:00,25.9,68.871664,49.477196,29.701442,21.193045,20.3,71.775536,103.582936,0
3,2006-10-25 05:38:00,27.2,65.658285,51.649763,28.820497,21.021897,20.6,70.589861,103.697800,0
4,2006-10-25 07:38:00,22.0,64.166553,46.851182,27.760388,20.975880,20.4,71.762377,103.680362,0
...,...,...,...,...,...,...,...,...,...,...
42201,2018-09-06 01:38:00,7.4,NaN,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
42202,2018-09-06 03:38:00,7.2,NaN,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
42203,2018-09-06 05:38:00,6.9,NaN,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
42204,2018-09-06 07:38:00,6.9,NaN,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
42205,2018-09-06 09:38:00,7.0,NaN,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [27]:
df1 = df1.rename(columns={
    'VAL356CI8017-Conductividad': 'Conductividad',
    'VAL356M014-Carga Motor': 'M014-Carga Motor',
    'VAL356M015-Carga Motor': 'M015-Carga Motor',
    'VAL356PI8026-Ind.Presión': 'PI8026-Ind.Presión',
    'VAL356PIC8025-Ind.Presión': 'PIC8025-Ind.Presión',
    'VAL356TI8015-Ind.Temperatura': 'TI8015-Ind.Temperatura',
    'VAL356TIC8014-Ind.Temperatura': 'TIC8014-Ind.Temperatura',
})
attrs = {
    'var': 'df1',
    'type': type(df1).__name__,  
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Fecha,Conductividad,VAL356M003-Carga Motor,M014-Carga Motor,M015-Carga Motor,PI8026-Ind.Presión,PIC8025-Ind.Presión,TI8015-Ind.Temperatura,TIC8014-Ind.Temperatura,Estado
0,2006-10-24 23:38:00,12.3,68.026459,45.670056,30.343173,21.492553,20.9,71.883617,103.414846,0
1,2006-10-25 01:38:00,18.9,68.827098,45.924569,30.126654,20.954956,20.6,72.301453,103.487449,0
2,2006-10-25 03:38:00,25.9,68.871664,49.477196,29.701442,21.193045,20.3,71.775536,103.582936,0
3,2006-10-25 05:38:00,27.2,65.658285,51.649763,28.820497,21.021897,20.6,70.589861,103.697800,0
4,2006-10-25 07:38:00,22.0,64.166553,46.851182,27.760388,20.975880,20.4,71.762377,103.680362,0
...,...,...,...,...,...,...,...,...,...,...
42201,2018-09-06 01:38:00,7.4,NaN,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
42202,2018-09-06 03:38:00,7.2,NaN,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
42203,2018-09-06 05:38:00,6.9,NaN,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
42204,2018-09-06 07:38:00,6.9,NaN,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
42205,2018-09-06 09:38:00,7.0,NaN,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [36]:
df1['Fecha'] = pd.to_datetime(df1['Fecha'], errors='coerce')

In [39]:
columnas_a_convertir = [
    'Conductividad',
    'M014-Carga Motor',
    'M015-Carga Motor',
    'PI8026-Ind.Presión',
    'PIC8025-Ind.Presión',
    'TI8015-Ind.Temperatura',
    'TIC8014-Ind.Temperatura',
    'Estado'
]

In [40]:
df1.columns = df1.columns.str.strip()

In [41]:
print(df1.columns.tolist())

['Fecha', 'VAL356CI8017-Conductividad', 'VAL356M003-Carga Motor', 'VAL356M014-Carga Motor', 'VAL356M015-Carga Motor', 'VAL356PI8026-Ind.Presión', 'VAL356PIC8025-Ind.Presión', 'VAL356TI8015-Ind.Temperatura', 'VAL356TIC8014-Ind.Temperatura', 'Estado']

In [42]:
columnas_a_convertir = [
    'Conductividad',
    'M014-Carga Motor',
    'M015-Carga Motor',
    'PI8026-Ind.Presión',
    'PIC8025-Ind.Presión',
    'TI8015-Ind.Temperatura',
    'TIC8014-Ind.Temperatura',
    'Estado'
]

In [46]:
for col in columnas_a_convertir:
    if col not in df1.columns:
        print(f"Columna: {col}")

Columna: Conductividad
Columna: M014-Carga Motor
Columna: M015-Carga Motor
Columna: PI8026-Ind.Presión
Columna: PIC8025-Ind.Presión
Columna: TI8015-Ind.Temperatura
Columna: TIC8014-Ind.Temperatura

In [52]:
df1 = df1.fillna(method='ffill')
attrs = {
    'var': 'df1',
    'type': type(df1).__name__,  
}
[attrs]
df1

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\565497250.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1 = df1.fillna(method='ffill')

[{'var': 'df1', 'type': 'DataFrame'}]

,Fecha,VAL356CI8017-Conductividad,VAL356M003-Carga Motor,VAL356M014-Carga Motor,VAL356M015-Carga Motor,VAL356PI8026-Ind.Presión,VAL356PIC8025-Ind.Presión,VAL356TI8015-Ind.Temperatura,VAL356TIC8014-Ind.Temperatura,Estado
0,2006-10-24 23:38:00,12.3,68.026459,45.670056,30.343173,21.492553,20.9,71.883617,103.414846,0
1,2006-10-25 01:38:00,18.9,68.827098,45.924569,30.126654,20.954956,20.6,72.301453,103.487449,0
2,2006-10-25 03:38:00,25.9,68.871664,49.477196,29.701442,21.193045,20.3,71.775536,103.582936,0
3,2006-10-25 05:38:00,27.2,65.658285,51.649763,28.820497,21.021897,20.6,70.589861,103.697800,0
4,2006-10-25 07:38:00,22.0,64.166553,46.851182,27.760388,20.975880,20.4,71.762377,103.680362,0
...,...,...,...,...,...,...,...,...,...,...
42201,2018-09-06 01:38:00,7.4,0.000000,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
42202,2018-09-06 03:38:00,7.2,0.000000,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
42203,2018-09-06 05:38:00,6.9,0.000000,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
42204,2018-09-06 07:38:00,6.9,0.000000,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
42205,2018-09-06 09:38:00,7.0,0.000000,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [54]:
cond = ((df1['Fecha'].ge(pd.to_datetime('2016-01-01 00:00:00', format='%Y-%m-%d %H:%M:%S', errors='coerce'))))
df1 = df1[cond]
attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Fecha,VAL356CI8017-Conductividad,VAL356M003-Carga Motor,VAL356M014-Carga Motor,VAL356M015-Carga Motor,VAL356PI8026-Ind.Presión,VAL356PIC8025-Ind.Presión,VAL356TI8015-Ind.Temperatura,VAL356TIC8014-Ind.Temperatura,Estado
30676,2016-01-08 11:38:00,4.5,0.0,69.658713,42.280192,18.769251,19.0,79.399877,99.160674,0
30677,2016-01-08 13:38:00,4.4,0.0,67.954487,42.381221,18.411020,19.0,78.184952,98.775669,0
30678,2016-01-08 15:38:00,4.2,0.0,69.688606,41.967134,18.601041,19.0,80.599028,101.165308,0
30679,2016-01-08 17:38:00,4.2,0.0,69.274182,42.124866,18.582166,19.0,79.301819,99.934365,0
30680,2016-01-08 19:38:00,4.2,0.0,69.095421,41.588124,18.593953,19.0,80.170472,100.804536,0
...,...,...,...,...,...,...,...,...,...,...
42201,2018-09-06 01:38:00,7.4,0.0,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
42202,2018-09-06 03:38:00,7.2,0.0,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
42203,2018-09-06 05:38:00,6.9,0.0,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
42204,2018-09-06 07:38:00,6.9,0.0,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
42205,2018-09-06 09:38:00,7.0,0.0,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [59]:

df1.columns = df1.columns.str.strip()

if 'Fecha' in df1.columns:
    df1.set_index('Fecha', inplace=True)
    print("Columna 'Fecha' usada como índice.")
else:
    print("La columna 'Fecha' no existe o ya no está en el DataFrame.")

attrs = {
    'var': 'df1',
    'type': type(df1).__name__,
}
[attrs]
df1

La columna 'Fecha' no existe o ya no está en el DataFrame.

[{'var': 'df1', 'type': 'DataFrame'}]

,VAL356CI8017-Conductividad,VAL356M003-Carga Motor,VAL356M014-Carga Motor,VAL356M015-Carga Motor,VAL356PI8026-Ind.Presión,VAL356PIC8025-Ind.Presión,VAL356TI8015-Ind.Temperatura,VAL356TIC8014-Ind.Temperatura,Estado
Fecha,,,,,,,,,
2016-01-08 11:38:00,4.5,0.0,69.658713,42.280192,18.769251,19.0,79.399877,99.160674,0
2016-01-08 13:38:00,4.4,0.0,67.954487,42.381221,18.411020,19.0,78.184952,98.775669,0
2016-01-08 15:38:00,4.2,0.0,69.688606,41.967134,18.601041,19.0,80.599028,101.165308,0
2016-01-08 17:38:00,4.2,0.0,69.274182,42.124866,18.582166,19.0,79.301819,99.934365,0
2016-01-08 19:38:00,4.2,0.0,69.095421,41.588124,18.593953,19.0,80.170472,100.804536,0
...,...,...,...,...,...,...,...,...,...
2018-09-06 01:38:00,7.4,0.0,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
2018-09-06 03:38:00,7.2,0.0,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
2018-09-06 05:38:00,6.9,0.0,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
2018-09-06 07:38:00,6.9,0.0,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
2018-09-06 09:38:00,7.0,0.0,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [66]:

df1.columns = df1.columns.str.strip()

if 'Conductividad' in df1.columns:
    cond = df1['Conductividad'].le(12)
    df1 = df1[cond]
else:
    print("La columna 'Conductividad' no existe.")

attrs = {
    'var': 'df1',
    'type': type(df1).__name__,
}
[attrs]
df1

La columna 'Conductividad' no existe.

[{'var': 'df1', 'type': 'DataFrame'}]

,VAL356CI8017-Conductividad,VAL356M003-Carga Motor,VAL356M014-Carga Motor,VAL356M015-Carga Motor,VAL356PI8026-Ind.Presión,VAL356PIC8025-Ind.Presión,VAL356TI8015-Ind.Temperatura,VAL356TIC8014-Ind.Temperatura,Estado
Fecha,,,,,,,,,
2016-01-08 11:38:00,4.5,0.0,69.658713,42.280192,18.769251,19.0,79.399877,99.160674,0
2016-01-08 13:38:00,4.4,0.0,67.954487,42.381221,18.411020,19.0,78.184952,98.775669,0
2016-01-08 15:38:00,4.2,0.0,69.688606,41.967134,18.601041,19.0,80.599028,101.165308,0
2016-01-08 17:38:00,4.2,0.0,69.274182,42.124866,18.582166,19.0,79.301819,99.934365,0
2016-01-08 19:38:00,4.2,0.0,69.095421,41.588124,18.593953,19.0,80.170472,100.804536,0
...,...,...,...,...,...,...,...,...,...
2018-09-06 01:38:00,7.4,0.0,72.696510,43.464317,19.695450,19.5,81.372489,99.598170,0
2018-09-06 03:38:00,7.2,0.0,72.905098,44.058929,19.826046,19.5,81.911505,99.633708,0
2018-09-06 05:38:00,6.9,0.0,72.968914,44.584087,19.523726,19.5,80.810454,99.775918,0
2018-09-06 07:38:00,6.9,0.0,72.905579,44.417335,19.308117,19.5,81.587220,100.136055,0
2018-09-06 09:38:00,7.0,0.0,72.956738,44.203780,19.335458,19.5,81.812438,100.482443,0

In [77]:
import pandas as pd
from functools import partial
from pandas.tseries.frequencies import to_offset


df1 = pd.DataFrame({
    'fecha': pd.date_range('2024-01-01 00:00:00', periods=10, freq='30T'),
    'valor': range(10)
})


def roundfunc(t, freq):
    freq = to_offset(freq)
    return pd.Timestamp((t.value // freq.delta.value) * freq.delta.value)


grouped = df1.groupby(df1['fecha'].apply(partial(roundfunc, freq='120T')))


attrs = {
    'var': 'grouped',
    'type': type(grouped).__name__,
}
print(attrs)


enum = enumerate(grouped.groups)
nextel = next(enum)


grupo_resultado = grouped.get_group(nextel[1])
print(grupo_resultado)

{'var': 'grouped', 'type': 'DataFrameGroupBy'}
                fecha  valor
0 2024-01-01 00:00:00      0
1 2024-01-01 00:30:00      1
2 2024-01-01 01:00:00      2
3 2024-01-01 01:30:00      3

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4129161513.py:7: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  'fecha': pd.date_range('2024-01-01 00:00:00', periods=10, freq='30T'),
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4129161513.py:13: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  freq = to_offset(freq)
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4129161513.py:14: FutureWarning: Minute.delta is deprecated and will be removed in a future version. Use pd.Timedelta(obj) instead
  return pd.Timestamp((t.value // freq.delta.value) * freq.delta.value)

In [86]:
import pandas as pd
from functools import partial
from pandas.tseries.frequencies import to_offset


df1 = pd.DataFrame({
    'fecha': pd.date_range('2024-01-01 00:00:00', periods=10, freq='30T'),
    'valor': range(10)
})


df1['fecha'] = pd.to_datetime(df1['fecha'])


def roundfunc(t, freq):
    freq = to_offset(freq)
    return pd.Timestamp((t.value // freq.delta.value) * freq.delta.value)


df1['fecha_redondeada'] = df1['fecha'].apply(partial(roundfunc, freq='120T'))


grouped = df1.groupby('fecha_redondeada')


df_median = grouped.aggregate('median')


attrs = {
    'var': 'df_median',
    'type': type(df_median).__name__,
    'shape': df_median.shape,
    'columns': list(df_median.columns),
}


print(attrs)
print(df_median)

{'var': 'df_median', 'type': 'DataFrame', 'shape': (3, 2), 'columns': ['fecha', 'valor']}
                                  fecha  valor
fecha_redondeada
2024-01-01 00:00:00 2024-01-01 00:45:00    1.5
2024-01-01 02:00:00 2024-01-01 02:45:00    5.5
2024-01-01 04:00:00 2024-01-01 04:15:00    8.5

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4042421110.py:7: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  'fecha': pd.date_range('2024-01-01 00:00:00', periods=10, freq='30T'),
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4042421110.py:16: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  freq = to_offset(freq)
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\4042421110.py:17: FutureWarning: Minute.delta is deprecated and will be removed in a future version. Use pd.Timedelta(obj) instead
  return pd.Timestamp((t.value // freq.delta.value) * freq.delta.value)

In [90]:
import pandas as pd


df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})


df1 = df1.aggregate('median')


attrs = {
    'var': 'df1',
    'type': type(df1).__name__,  
}


print(attrs)
print(df1)

{'var': 'df1', 'type': 'Series'}
A    2.0
B    5.0
dtype: float64

In [102]:
import os
import pandas as pd


df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})


carpeta = os.path.expanduser('~/Documents/Repositorio')
os.makedirs(carpeta, exist_ok=True)


archivo = os.path.join(carpeta, 'COMPUAPLI.csv')


df1.to_csv(archivo, index=False)
print(f'✅ Archivo guardado en: {archivo}')

✅ Archivo guardado en: C:\Users\Usuario/Documents/Repositorio\COMPUAPLI.csv

In [99]:
import os
import pandas as pd

file = os.path.join('C:/', 'COMPUAPLI.csv')

if not os.path.exists(file):
    raise FileNotFoundError(f'⚠️ Archivo no encontrado en: {file}')

df12 = pd.read_csv(file, header=0)

attrs = {
    'var': 'df12',
    'type': type(df12).__name__,
}

print(attrs)
print(df12)

                     Fecha  Conductividad  M014-Carga Motor  M015-Carga Motor  \
0      2016-01-08 10:00:00            4.5         69.658713         42.280192
1      2016-01-08 12:00:00            4.4         67.954487         42.381221
2      2016-01-08 14:00:00            4.2         69.688606         41.967134
3      2016-01-08 16:00:00            4.2         69.274182         42.124866
4      2016-01-08 18:00:00            4.2         69.095421         41.588124
...                    ...            ...               ...               ...
11161  2018-09-06 00:00:00            7.4         72.696510         43.464317
11162  2018-09-06 02:00:00            7.2         72.905098         44.058929
11163  2018-09-06 04:00:00            6.9         72.968914         44.584087
11164  2018-09-06 06:00:00            6.9         72.905579         44.417335
11165  2018-09-06 08:00:00            7.0         72.956738         44.203780

       PI8026-Ind.Presión  PIC8025-Ind.Presión  TI8015-Ind.Temperatura  \
0               18.769251                 19.0               79.399877
1               18.411020                 19.0               78.184952
2               18.601041                 19.0               80.599028
3               18.582166                 19.0               79.301819
4               18.593953                 19.0               80.170472
...                   ...                  ...                     ...
11161           19.695450                 19.5               81.372489
11162           19.826046                 19.5               81.911505
11163           19.523726                 19.5               80.810454
11164           19.308117                 19.5               81.587220
11165           19.335458                 19.5               81.812438

       TIC8014-Ind.Temperatura  Estado
0                    99.160674     0.0
1                    98.775669     0.0
2                   101.165308     0.0
3                    99.934365     0.0
4                   100.804536     0.0
...                        ...     ...
11161                99.598170     0.0
11162                99.633708     0.0
11163                99.775918     0.0
11164               100.136055     0.0
11165               100.482443     0.0

[11166 rows x 9 columns]

In [135]:
import os
print(os.getcwd())

C:\Users\Usuario

In [137]:
import pandas as pd




data = {'  Fecha  ': ['2023-01-01', '2023-01-02'], 'Value': [10, 20]}
df12 = pd.DataFrame(data)


print("Original columns before cleaning:", df12.columns)


df12.columns = df12.columns.str.strip()

print("Columns after stripping whitespace:", df12.columns)


if df12['Fecha'].isnull().all():
    print("Warning: All 'Fecha' values became NaT during conversion. Check original data format.")
    


df12['Fecha'] = pd.to_datetime(df12['Fecha'], errors='coerce')



df12.set_index('Fecha', inplace=True)

print("\nDataFrame head after setting index:")
print(df12.head())

Original columns before cleaning: Index(['  Fecha  ', 'Value'], dtype='object')
Columns after stripping whitespace: Index(['Fecha', 'Value'], dtype='object')

DataFrame head after setting index:
            Value
Fecha
2023-01-01     10
2023-01-02     20

In [157]:

cols_to_drop = [
    'TIC8014-Ind.Temperatura',
    'TI8015-Ind.Temperatura',
    'PIC8025-Ind.Presión',
    'PI8026-Ind.Presión',
    'M015-Carga Motor',
    'Conductividad',
    'M014-Carga Motor'
]


if 'df12' in globals():
    
    
    existing_cols_to_drop = [col for col in cols_to_drop if col in df12.columns]
    
    
    df15 = df12.drop(existing_cols_to_drop, axis='columns')
    
    
    not_found_cols = set(cols_to_drop) - set(existing_cols_to_drop)
    if not_found_cols:
        print("Advertencia: Las siguientes columnas no se encontraron en df12 y no pudieron ser eliminadas:", list(not_found_cols))
    else:
        print("Todas las columnas especificadas para eliminar fueron encontradas y eliminadas exitosamente.")

    
    if isinstance(df15, pd.DataFrame):
        attrs = {
            'var': 'df15',
            'type': type(df15).__name__
        }
        print(attrs)
        print(df15.head())
    else:
        print("Error: df15 no es un DataFrame válido.")

else:
    print("Error: El DataFrame 'df12' no está definido.")

Advertencia: Las siguientes columnas no se encontraron en df12 y no pudieron ser eliminadas: ['TIC8014-Ind.Temperatura', 'PIC8025-Ind.Presión', 'Conductividad', 'M015-Carga Motor', 'PI8026-Ind.Presión', 'TI8015-Ind.Temperatura', 'M014-Carga Motor']
{'var': 'df15', 'type': 'DataFrame'}
            Value
Fecha
2023-01-01     10
2023-01-02     20

In [160]:
import pandas as pd


column_to_select = 'Estado'


if column_to_select in df12.columns:
    df16 = df12[[column_to_select]] 
    
    
    attrs = {
        'variable_name': 'df16', 
        'variable_type': type(df16).__name__,
        'shape': df16.shape, 
        'column_selected': column_to_select,
        'dtype': df16[column_to_select].dtype 
    }
    
    
    print(f"DataFrame '{column_to_select}' creado exitosamente.")
    print("Atributos de df16:")
    print(attrs)
    
    print(f"\nPrimeras 5 filas de df16 (columna '{column_to_select}'):")
    print(df16.head())
    
    
    print("\nInformación general de df16:")
    df16.info()
    
    if df16[column_to_select].nunique() < 20: 
        print(f"\nConteo de valores únicos para '{column_to_select}':")
        print(df16[column_to_select].value_counts())

else:
    
    print(f"Error: La columna '{column_to_select}' no se encontró en el DataFrame df12.")
    df16 = pd.DataFrame() 
    attrs = {
        'variable_name': 'df16',
        'variable_type': type(df16).__name__,
        'status': 'empty_due_to_missing_column',
        'missing_column': column_to_select
    }
    print("Atributos de df16 (vacío debido al error):")
    print(attrs)

Error: La columna 'Estado' no se encontró en el DataFrame df12.
Atributos de df16 (vacío debido al error):
{'variable_name': 'df16', 'variable_type': 'DataFrame', 'status': 'empty_due_to_missing_column', 'missing_column': 'Estado'}

In [165]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import logging


logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')


def encode_categorical_columns(df: pd.DataFrame) -> pd.DataFrame:
    df_encoded = df.copy()
    cat_cols = df_encoded.select_dtypes(include=['category']).columns
    for col in cat_cols:
        df_encoded[col] = df_encoded[col].cat.codes
    return df_encoded


def create_datetime_windows(dfx, dfy, dfy_total, size, periods, y_choice='last', ahead=''):
    x_windowed = []
    y_windowed = []
    window_indices = []

    if not isinstance(dfx.index, pd.DatetimeIndex) or not isinstance(dfy.index, pd.DatetimeIndex):
        raise TypeError("Los DataFrames deben tener índices de tipo DatetimeIndex.")

    def _process_window(window_series):
        current_window_indices = window_series.index
        if len(current_window_indices) != periods:
            return None

        if y_choice == 'ahead':
            try:
                future_index = current_window_indices[-1] + pd.Timedelta(ahead)
                wy = dfy_total.loc[[future_index]]
                if wy.empty:
                    return None
                wx = dfx.loc[current_window_indices]
                x_windowed.append(wx)
                y_windowed.append(wy)
                window_indices.append(current_window_indices[0])
            except Exception:
                return None
        else:
            wx = dfx.loc[current_window_indices]
            wy = dfy.loc[current_window_indices]
            if y_choice == 'last':
                wy = wy.iloc[-1]
            elif y_choice == 'first':
                wy = wy.iloc[0]
            x_windowed.append(wx)
            y_windowed.append(wy)
            window_indices.append(current_window_indices[0])
        return 0

    dfx.iloc[:, 0].rolling(window=size, min_periods=periods).apply(lambda w: _process_window(w), raw=False)
    return x_windowed, y_windowed, window_indices


def get_list_shape_string(data_list: list) -> str:
    if not data_list:
        return 'empty'
    first_element = data_list[0]
    if isinstance(first_element, (np.ndarray, pd.DataFrame, pd.Series)):
        shape_str = str(first_element.shape)
    else:
        try:
            shape_str = str(np.array(first_element).shape)
        except Exception:
            shape_str = "unknown_shape"
    return f"{len(data_list)} x {shape_str}"


def normal_anomal_split(dfx, dfy, size, periods, y_choice='last', ahead='', custom_normal_split=False, normal_test_ratio=0.1, scaler_type='MinMaxScaler'):
    scaler_map = {
        'MinMaxScaler': MinMaxScaler(),
        'StandardScaler': StandardScaler(),
        'RobustScaler': RobustScaler()
    }
    myscaler = scaler_map.get(scaler_type)
    if myscaler is None:
        raise ValueError(f"Escalador no válido: {scaler_type}")

    dfx_encoded = encode_categorical_columns(dfx)
    dfy_encoded = encode_categorical_columns(dfy)

    x_windowed, y_windowed, windows_ind = create_datetime_windows(dfx_encoded, dfy_encoded, dfy_encoded, size, periods, y_choice, ahead)
    if not x_windowed:
        return {'x_train': np.array([]), 'x_test': np.array([]), 'y_test': np.array([]), 'x_mix': np.array([]), 'y_mix': np.array([]), 'i_mix': [], 'myscaler': myscaler}

    x_normal, y_normal = [], []
    x_anomal, y_anomal = [], []

    for i, wy in enumerate(y_windowed):
        label = wy.iloc[0].item() if isinstance(wy, (pd.Series, pd.DataFrame)) else wy
        if label == 0:
            x_normal.append(x_windowed[i])
            y_normal.append(y_windowed[i])
        else:
            x_anomal.append(x_windowed[i])
            y_anomal.append(y_windowed[i])

    normal_indices = np.arange(len(x_normal))
    np.random.shuffle(normal_indices)

    if custom_normal_split:
        length_test_normal = round(len(x_normal) * normal_test_ratio)
    else:
        length_test_normal = min(len(x_anomal), len(x_normal) - 1)

    normal_test_indices = normal_indices[:length_test_normal]
    normal_train_indices = normal_indices[length_test_normal:]

    x_normal_train = [x_normal[i] for i in normal_train_indices]
    x_normal_test = [x_normal[i] for i in normal_test_indices]

    x_normal_train_filtered = [df for df in x_normal_train if not df.empty]
    x_normal_train_total_flat = pd.concat(x_normal_train_filtered).to_numpy() if x_normal_train_filtered else np.array([])

    is_scaler_fitted = False
    if x_normal_train_total_flat.size > 0:
        try:
            myscaler.fit(x_normal_train_total_flat)
            is_scaler_fitted = True
        except Exception:
            pass

    def _scale_and_squeeze(data_list, scaler_obj):
        scaled_list = []
        for item_df in data_list:
            if item_df.empty or not hasattr(scaler_obj, 'scale_'):
                scaled_list.append(np.array([]))
                continue
            scaled_array = scaler_obj.transform(item_df.to_numpy())
            if scaled_array.ndim > 1 and scaled_array.shape[1] == 1:
                scaled_list.append(np.squeeze(scaled_array, axis=1))
            else:
                scaled_list.append(scaled_array)
        return scaled_list

    x_train_scaled = _scale_and_squeeze(x_normal_train, myscaler) if is_scaler_fitted else []
    x_test_normal_scaled = _scale_and_squeeze(x_normal_test, myscaler) if is_scaler_fitted else []
    x_anomal_scaled = _scale_and_squeeze(x_anomal, myscaler) if is_scaler_fitted else []
    x_mix_scaled = _scale_and_squeeze(x_windowed, myscaler) if is_scaler_fitted else []

    y_test = [0] * len(x_test_normal_scaled) + [1] * len(x_anomal_scaled)
    x_test = x_test_normal_scaled + x_anomal_scaled

    y_mix = [wy.iloc[0].item() if isinstance(wy, (pd.Series, pd.DataFrame)) else wy for wy in y_windowed]

    return {
        'x_train': np.array(x_train_scaled, dtype=object),
        'x_test': np.array(x_test, dtype=object),
        'y_test': np.array(y_test),
        'x_mix': np.array(x_mix_scaled, dtype=object),
        'y_mix': np.array(y_mix),
        'i_mix': windows_ind,
        'myscaler': myscaler,
    }




dates = pd.date_range(start='2023-01-01', periods=1000, freq='10T')


data_x = {
    'feature1': np.random.rand(1000),
    'feature2': np.random.randint(0, 5, 1000),
    'category_col': pd.Series(np.random.choice(['A', 'B', 'C'], 1000), dtype='category')
}
df15_features = pd.DataFrame(data_x, index=dates)


labels = np.zeros(1000)
labels[np.random.choice(1000, 50, replace=False)] = 1
data_y = {
    'Estado': pd.Series(labels, dtype='category'),
    'other_info': np.random.rand(1000)
}
df16_labels = pd.DataFrame(data_y, index=dates)


results = normal_anomal_split(
    dfx=df15_features,
    dfy=df16_labels,
    size='600T',
    periods=60,
    y_choice='last',
    custom_normal_split=True,
    normal_test_ratio=0.2,
    scaler_type='MinMaxScaler'
)


print("--- Resultados ---")
print("x_train shape:", results['x_train'].shape)
print("x_test shape:", results['x_test'].shape)
print("y_test shape:", results['y_test'].shape)
print("y_mix:", results['y_mix'][:5])
print("Índices de ventanas:", results['i_mix'][:5])

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\3695717672.py:165: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  dates = pd.date_range(start='2023-01-01', periods=1000, freq='10T')
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19656\3695717672.py:55: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  dfx.iloc[:, 0].rolling(window=size, min_periods=periods).apply(lambda w: _process_window(w), raw=False)

--- Resultados ---
x_train shape: (0,)
x_test shape: (0,)
y_test shape: (0,)
y_mix: [-1. -1. -1. -1. -1.]
Índices de ventanas: [Timestamp('2023-01-01 00:00:00'), Timestamp('2023-01-01 00:10:00'), Timestamp('2023-01-01 00:20:00'), Timestamp('2023-01-01 00:30:00'), Timestamp('2023-01-01 00:40:00')]

In [167]:
import os
import joblib
import numpy as np


base_path = 'C:/Users/Alumno/Desktop/computacion aplicada/c2/'


os.makedirs(base_path, exist_ok=True)


np.savez(
    file=os.path.join(base_path, 'Informe final Reboiler NPZ'),
    x_train=df15['x_train'],
    x_test=df15['x_test'],
    y_test=df15['y_test'],
    x_mix=df15['x_mix'],
    y_mix=df15['y_mix'],
    i_mix=df15['i_mix']
)


joblib.dump(df15['myscaler'], os.path.join(base_path, 'scaler.joblib'))

PermissionError: [WinError 5] Acceso denegado: 'C:/Users/Alumno'